[package]
name = "rv32-emulator"
version = "0.2.0"
edition = "2021"

[profile.release]
lto = true
strip = true
opt-level = 3

[dependencies]
goblin = "0.9.3"
log = "0.4.25"
structopt = "0.3.26"

[dependencies.riscv-vm]
path = "riscv-vm"
features = ["logging"]
